router.get("/:id/comments", (req, res) => {
    var promises = []
    var commentsfound = []

    //Muestra todos los comentarios del usuario buscando en Comments colection                ¿Aquí podría poner un throw en cada .then poniendo la clase de error que sería y luego al final en el .catch se recogen todos esos throw (errores) y se hace console.log?????
    User.find({ _id : req.params.id})
    .then(user => {
        
        for (i in user[0].comments){
            var comment_id = user[0].comments[i];
            promises.push(
                Comment.find({_id : comment_id})
                .then(comment => {commentsfound.push(comment[0])})
            )
        }

        Promise.all(promises)
        .then(() => {res.send(commentsfound)
        })

    })
    .catch(error => console.log(error))
})